//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWebServiceCuil")]
public interface IWebServiceCuil
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceCuil/DoWork", ReplyAction="http://tempuri.org/IWebServiceCuil/DoWorkResponse")]
    void DoWork();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceCuil/DoWork", ReplyAction="http://tempuri.org/IWebServiceCuil/DoWorkResponse")]
    System.Threading.Tasks.Task DoWorkAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceCuil/getCuil", ReplyAction="http://tempuri.org/IWebServiceCuil/getCuilResponse")]
    string getCuil(string apellidoYNombre, string genero);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceCuil/getCuil", ReplyAction="http://tempuri.org/IWebServiceCuil/getCuilResponse")]
    System.Threading.Tasks.Task<string> getCuilAsync(string apellidoYNombre, string genero);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWebServiceCuilChannel : IWebServiceCuil, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebServiceCuilClient : System.ServiceModel.ClientBase<IWebServiceCuil>, IWebServiceCuil
{
    
    public WebServiceCuilClient()
    {
    }
    
    public WebServiceCuilClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebServiceCuilClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceCuilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceCuilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void DoWork()
    {
        base.Channel.DoWork();
    }
    
    public System.Threading.Tasks.Task DoWorkAsync()
    {
        return base.Channel.DoWorkAsync();
    }
    
    public string getCuil(string apellidoYNombre, string genero)
    {
        return base.Channel.getCuil(apellidoYNombre, genero);
    }
    
    public System.Threading.Tasks.Task<string> getCuilAsync(string apellidoYNombre, string genero)
    {
        return base.Channel.getCuilAsync(apellidoYNombre, genero);
    }
}
